#!/usr/bin/env python3

import argparse
import json
import sys

from jsonExplorer import FunnyJsonExplorer


def main():
    parser = argparse.ArgumentParser(description="JSON Explorer")
    parser.add_argument('-f', '--file', type=str, required=True)
    parser.add_argument('-s', '--style', type=str, required=False, default='tree')
    parser.add_argument('-i', '--icon', type=str, required=False, default='poker')
    parser.add_argument('-c', '--config', type=str, required=False, default='./src/config/icon.json')
    args = parser.parse_args()

    try:
        explorer = FunnyJsonExplorer(args.style, args.icon, args.config)
        explorer._load(args.file)
        explorer.build()
        explorer.show()

    except FileNotFoundError:
        print(f"Error: The file {args.file} was not found.")
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"Error: The file {args.file} is not a valid JSON file.")
        sys.exit(1)


if __name__ == "__main__":
    main()
